# Generated by Django 4.1.6 on 2023-05-22 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_alter_template_product_price'),
        ('survey', '0002_initial'),
        ('cart', '0003_alter_cart_survey_alter_cart_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_set', to='survey.survey', verbose_name='설문'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_set', to='template.template', verbose_name='템플릿'),
        ),
    ]
