# Generated by Django 4.1.6 on 2023-06-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
        ('template', '0003_alter_template_gift_sent_count'),
        ('cart', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template', verbose_name='템플릿'),
        ),
    ]
