# Generated by Django 4.1.6 on 2023-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('kakaoId', models.BigIntegerField(default=1, verbose_name='카카오 id')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='카카오 이메일')),
                ('realName', models.CharField(max_length=30, null=True, verbose_name='실명')),
                ('phoneNumber', models.CharField(max_length=20, null=True, verbose_name='전화번호')),
                ('gender', models.BooleanField(null=True, verbose_name='성별')),
                ('birth', models.DateField(max_length=20, null=True, verbose_name='생년월일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
