# Generated by Django 4.1.6 on 2023-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakaoId',
            field=models.BigIntegerField(default=1, verbose_name='카카오 id'),
        ),
    ]
