# Generated by Django 4.1.6 on 2023-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(1, 'man'), (2, 'woman')], default=1, verbose_name='성별'),
        ),
    ]
