# Generated by Django 4.1.6 on 2023-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(max_length=20, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'man'), (2, 'woman')], verbose_name='성별'),
        ),
    ]
