# Generated by Django 4.1.6 on 2023-03-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_birth_alter_user_gender'),
        ('user', '0002_alter_user_profileimage'),
    ]

    operations = [
    ]
