# Generated by Django 4.1.6 on 2023-03-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20230327_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(max_length=20, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(1, 'man'), (2, 'woman')], verbose_name='성별'),
        ),
    ]
