# Generated by Django 4.1.6 on 2023-05-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(max_length=20, null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='realName',
            field=models.CharField(max_length=30, null=True, verbose_name='실명'),
        ),
    ]
