# Generated by Django 4.1.6 on 2023-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_birth_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakaoId',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='카카오 id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='카카오 계정 이메일'),
        ),
    ]
