# Generated by Django 4.1.6 on 2023-05-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_kakaoid_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='카카오 계정 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakaoId',
            field=models.IntegerField(default=0, verbose_name='카카오 id'),
        ),
    ]
