# Generated by Django 4.1.6 on 2023-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_token', models.CharField(max_length=200, verbose_name='템플릿 토큰')),
                ('template_name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('template_trace_id', models.BigIntegerField(verbose_name='템플릿 ID')),
                ('start_at', models.CharField(max_length=50, verbose_name='발송 가능 시작 일시')),
                ('end_at', models.CharField(max_length=50, verbose_name='발송 가능 종료 일시')),
                ('order_template_status', models.CharField(max_length=100, verbose_name='템플릿 상태')),
                ('budget_type', models.CharField(max_length=100, verbose_name='한도 타입')),
                ('gift_budget_count', models.IntegerField(verbose_name='발송 한도 수')),
                ('gift_sent_count', models.IntegerField(verbose_name='기발송 수')),
                ('gift_stock_count', models.IntegerField(verbose_name='발송 가능 수')),
                ('bm_sender_name', models.CharField(max_length=100, verbose_name='발신자 명')),
                ('mc_image_url', models.URLField(verbose_name='메세지카드 입력값')),
                ('mc_text', models.TextField(verbose_name='메세지카드 입력값')),
                ('product', models.JSONField(verbose_name='템플릿 상품 정보')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'template',
            },
        ),
    ]
