# Generated by Django 4.1.6 on 2023-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='item_type',
            field=models.CharField(default='', max_length=100, verbose_name='상품 유형'),
        ),
        migrations.AlterField(
            model_name='template',
            name='product_name',
            field=models.CharField(default='', max_length=100, verbose_name='상품명'),
        ),
    ]
