# Generated by Django 4.1.6 on 2023-05-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='product_detail_url',
            field=models.URLField(default='', verbose_name='상품 상세보기 URL'),
        ),
    ]
