# Generated by Django 4.1.6 on 2023-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_template_product_detail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='gift_sent_count',
            field=models.PositiveIntegerField(verbose_name='보낸 템플릿 개수'),
        ),
    ]
