# Generated by Django 4.1.6 on 2023-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(max_length=255)),
                ('data', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'idle'), (1, 'ongoing'), (2, 'done'), (3, 'awarded')], default=0, verbose_name='설문 상태')),
                ('is_survey_hidden', models.BooleanField(default=False, verbose_name='공개_비공개_여부')),
                ('end_at', models.DateTimeField(verbose_name='설문 종료 일시')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
