# Generated by Django 4.1.6 on 2023-03-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_options_alter_survey_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('type', models.CharField(max_length=255, verbose_name='카테고리 타입')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.AlterField(
            model_name='survey',
            name='data',
            field=models.JSONField(verbose_name='설문 데이터'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='thumbnail',
            field=models.URLField(max_length=255, verbose_name='설문 썸네일'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, verbose_name='설문 제목'),
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.category', verbose_name='카테고리'),
        ),
    ]
