# Generated by Django 4.1.6 on 2023-05-24 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_awarded',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_idle',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='결제 여부'),
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('END', 'END')], default='NOT_STARTED', max_length=20, verbose_name='설문 상태'),
        ),
        migrations.AddField(
            model_name='survey',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='설문 작성자'),
        ),
    ]
