# Generated by Django 4.1.6 on 2023-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='thumbnail',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='설문 썸네일'),
        ),
    ]
