# Generated by Django 4.1.6 on 2023-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_at',
            field=models.DateTimeField(null=True, verbose_name='설문 종료 일시'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='thumbnail',
            field=models.URLField(max_length=255, null=True, verbose_name='설문 썸네일'),
        ),
    ]
