# Generated by Django 4.1.6 on 2023-06-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_at',
            field=models.DateField(null=True, verbose_name='설문 종료 일시'),
        ),
    ]
