# Generated by Django 4.1.6 on 2023-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='설문 시작 일시'),
        ),
    ]
