# Generated by Django 4.1.6 on 2023-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='기프티콘 결제 여부'),
        ),
    ]
