# Generated by Django 4.1.6 on 2023-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_awarded',
            field=models.BooleanField(default=False, verbose_name='설문 보상 지급 완료 여부'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_idle',
            field=models.BooleanField(default=True, verbose_name='설문 임시 저장 상태 여부'),
        ),
    ]
