# Generated by Django 4.1.6 on 2023-03-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_category_alter_survey_data_alter_survey_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
