# Generated by Django 4.1.6 on 2023-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_end_at_alter_survey_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_idle',
            field=models.BooleanField(default=True, verbose_name='임시 저장 여부'),
        ),
    ]
