# Generated by Django 4.1.6 on 2023-06-15 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_alter_survey_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='writer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='설문 작성자'),
        ),
    ]
