# Generated by Django 4.1.6 on 2023-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_survey_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='started_at',
            field=models.DateField(null=True, verbose_name='설문 시작 일시'),
        ),
    ]
