# Generated by Django 4.1.6 on 2023-05-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_survey_is_awarded_remove_survey_is_idle_and_more'),
        ('survey', '0003_survey_is_paid'),
    ]

    operations = [
    ]
