# Generated by Django 4.1.6 on 2023-03-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='data',
            field=models.JSONField(null=True, verbose_name='설문 데이터'),
        ),
    ]
