# Generated by Django 4.1.6 on 2023-05-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['id'], 'verbose_name': 'Survey', 'verbose_name_plural': 'Surveys'},
        ),
    ]
