# Generated by Django 4.1.6 on 2023-05-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0002_initial'),
        ('template', '0001_initial'),
        ('survey', '0006_alter_survey_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_token', models.CharField(max_length=200, verbose_name='템플릿 토큰')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='설문 객체')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
    ]
