# Generated by Django 4.1.6 on 2023-05-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_initial'),
        ('template', '0002_alter_template_product_price'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문'),
        ),
        migrations.AddField(
            model_name='order',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.template', verbose_name='템플릿'),
        ),
    ]
