# Generated by Django 4.1.6 on 2023-05-19 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_initial'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='template_token',
        ),
        migrations.AlterField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='템플릿 수신자'),
        ),
    ]
