# Generated by Django 4.1.6 on 2023-06-05 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_initial'),
        ('order', '0004_remove_order_receiver_order_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='winner',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='템플릿 수신자'),
        ),
    ]
