# Generated by Django 4.1.6 on 2023-06-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_survey_alter_cart_template'),
        ('order', '0005_remove_order_winner_order_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='order',
            name='template',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='장바구니'),
        ),
    ]
