# Generated by Django 4.1.6 on 2023-03-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('template', models.BigIntegerField(verbose_name='템플릿')),
                ('price', models.BigIntegerField(verbose_name='가격')),
                ('productImage', models.CharField(max_length=45, verbose_name='상품 이미지')),
                ('productName', models.CharField(max_length=45, verbose_name='상품 이름')),
                ('gifticonType', models.CharField(max_length=45, verbose_name='기프티콘 유형')),
            ],
            options={
                'verbose_name': 'Gifticon',
                'verbose_name_plural': 'Gifticons',
                'db_table': 'gifticon',
            },
        ),
        migrations.CreateModel(
            name='SurveyGifticon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('count', models.BigIntegerField(verbose_name='기프티콘 총개수')),
                ('gifticonCount', models.BigIntegerField(verbose_name='기프티콘 개수')),
                ('receiver', models.CharField(max_length=45, verbose_name='받는 분')),
                ('gifticon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifticon.gifticon', verbose_name='설문 ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문 ID')),
            ],
            options={
                'verbose_name': 'surveyGifticon',
                'verbose_name_plural': 'surveyGifticons',
                'db_table': 'surveyGifticon',
            },
        ),
    ]
