# Generated by Django 4.1.6 on 2023-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifticon', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveygifticon',
            name='receiver',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='받는 분'),
        ),
    ]
