# Generated by Django 4.1.6 on 2023-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
        ('gifticon', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveygifticon',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문'),
        ),
    ]
