# Generated by Django 4.1.6 on 2023-03-27 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
        ('gifticon', '0002_alter_gifticon_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveygifticon',
            name='gifticon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifticon.gifticon', verbose_name='기프티콘'),
        ),
        migrations.AlterField(
            model_name='surveygifticon',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='설문'),
        ),
    ]
