# Generated by Django 4.1.6 on 2023-03-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('gifticon', '0003_alter_surveygifticon_gifticon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveygifticon',
            name='receiver',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.CASCADE, to='participant.participant', verbose_name='받는 분'),
        ),
    ]
